apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziti-router.fullname" . }}-enrolment-jwt
type: Opaque
data:
  enrolmentJwt: {{ required "You must set .Values.enrolmentJwt to the edge routers enrolment token. Try adding --set-file enrolmentJwt=/tmp/router.jwt to your Helm command" .Values.enrolmentJwt | b64enc }}
